### ISSUE TITLE
Set SPARK_VERSION to 2 by default

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/flintstone#4]
I am currently updating some code and my spark jobs on the cluster failed with cryptic error message. When I ran flintstone with `SPARK_VERSION=2` my jobs ran successfully (aside from my own bugs, of course). I suggest `SPARK_VERSION` to default to `2` instead of `current` as it does currently.
@saalfeldlab/lab Any objections?

**Comment by igorpisarev** [comment]
I agree that 2 should be the default. I have not used Spark 1.6 in a long time, it is more of a legacy version now.

I would also suggest to set `TERMINATE=1` by default as it seems to be the most frequently used configuration and helps to avoid unnecessary costs.

**Comment by axtimwalde** [comment]
+1
